
package annotation;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "MyCompany", targetNamespace = "http://annotation/")
@XmlSeeAlso({ ObjectFactory.class })
public interface MyCompany {


    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployeeToDept", targetNamespace = "http://annotation/",
                    className = "annotation.AddEmployeeToDept")
    @ResponseWrapper(localName = "addEmployeeToDeptResponse", targetNamespace = "http://annotation/",
                     className = "annotation.AddEmployeeToDeptResponse")
    @Action(input = "http://annotation/MyCompany/addEmployeeToDeptRequest",
            output = "http://annotation/MyCompany/addEmployeeToDeptResponse")
    public boolean addEmployeeToDept(@WebParam(name = "arg0", targetNamespace = "") Emp arg0,
                                     @WebParam(name = "arg1", targetNamespace = "") int arg1);

    /**
     *
     * @return
     *     returns java.util.List<annotation.Dept>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyDepts", targetNamespace = "http://annotation/",
                    className = "annotation.GetMyDepts")
    @ResponseWrapper(localName = "getMyDeptsResponse", targetNamespace = "http://annotation/",
                     className = "annotation.GetMyDeptsResponse")
    @Action(input = "http://annotation/MyCompany/getMyDeptsRequest",
            output = "http://annotation/MyCompany/getMyDeptsResponse")
    public List<Dept> getMyDepts();

    /**
     *
     * @param arg0
     * @return
     *     returns annotation.Dept
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeptInfo", targetNamespace = "http://annotation/",
                    className = "annotation.GetDeptInfo")
    @ResponseWrapper(localName = "getDeptInfoResponse", targetNamespace = "http://annotation/",
                     className = "annotation.GetDeptInfoResponse")
    @Action(input = "http://annotation/MyCompany/getDeptInfoRequest",
            output = "http://annotation/MyCompany/getDeptInfoResponse")
    public Dept getDeptInfo(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setMyDepts", targetNamespace = "http://annotation/",
                    className = "annotation.SetMyDepts")
    @ResponseWrapper(localName = "setMyDeptsResponse", targetNamespace = "http://annotation/",
                     className = "annotation.SetMyDeptsResponse")
    @Action(input = "http://annotation/MyCompany/setMyDeptsRequest",
            output = "http://annotation/MyCompany/setMyDeptsResponse")
    public void setMyDepts(@WebParam(name = "arg0", targetNamespace = "") List<Dept> arg0);

}
