package demo.model;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 08 11:21:23 ART 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpByEmailRowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpByEmailRowImpl() {
    }
}

